<?xml version="1.0"?>
<package format="2">
  <name>rox_argo_kinematics</name>
  <version>1.0.0</version>
  <description>ROS 1 package for ROX Argo Kinematics from Neobotix (ported from ROS 2)</description>
  <maintainer email="ros@neobotix.de">Pradheep Padmanabhan</maintainer>
  <license>BSD</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>roscpp</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>trajectory_msgs</depend>
  <depend>neo_msgs</depend>
  <depend>neo_srvs</depend>
  <depend>tf</depend>
  <depend>tf2_ros</depend>
  <depend>nav_msgs</depend>
  <depend>angles</depend>

  <export>
  </export>
</package> 